#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_urdf.py  ->  urdf/lafengparrot.urdf

Single frozen source:
  - kinematics.json  (links, joints: parent/child/origin_mm/axis/limit_deg/effort/velocity)
  - inertials.json   (per-link mass_g, com_m, inertia_kgm2)

Units in the URDF: meters, kilograms, kg*m^2, radians, N*m, rad/s.
Floating base: the trunk link (URDF root = "base_link") has NO parent joint.
"""
import os
import json
import math
import importlib.util

HERE = os.path.dirname(os.path.abspath(__file__))
KIN_PATH = os.path.join(HERE, "kinematics.json")
INER_PATH = os.path.join(HERE, "inertials.json")
OUT_PATH = os.path.join(HERE, "urdf", "lafengparrot.urdf")

# The root segment is called "trunk" in the CAD/source data; in URDF/ROS the
# floating root link is conventionally named "base_link". Mesh files are still
# CAD-named (trunk.stl), so mesh stems use the SOURCE link name.
ROOT_URDF_NAME = "base_link"
LINK_NAME_MAP = {"trunk": ROOT_URDF_NAME}


def urdf_name(src_name: str) -> str:
    return LINK_NAME_MAP.get(src_name, src_name)


def deg2rad(d):
    return d * math.pi / 180.0


def fmt(v):
    # compact, loss-enough float formatting (m, kg, kg*m^2)
    return f"{v:.10g}"


def build():
    with open(KIN_PATH, "r", encoding="utf-8") as f:
        kin = json.load(f)
    with open(INER_PATH, "r", encoding="utf-8") as f:
        iner = json.load(f)

    links_src = kin["links"]
    joints = kin["joints"]
    iner_links = iner["links"]

    # In this source, each joint "origin" is the GLOBAL (trunk-frame) placement
    # of the child axis -- it is identical to the child link's frame_origin.
    # URDF <origin> is PARENT-RELATIVE, so subtract the parent link frame.
    frame_origin_mm = {lk["name"]: lk["frame_origin"] for lk in links_src}

    lines = []
    lines.append('<?xml version="1.0"?>')
    lines.append('<robot name="lafengparrot">')
    lines.append('')
    lines.append('  <!-- ============================================================')
    lines.append('       LaFengParrot REV-B 2026-09-27, generated by make_urdf.py')
    lines.append('       single source: kinematics.json + inertials.json')
    lines.append('       frame: +X forward(beak), +Y parrot-left, +Z up; origin = hip plane z=0')
    lines.append('       units: m / kg / kg*m^2 / rad / N*m / rad/s')
    lines.append('       ============================================================ -->')
    lines.append('')
    lines.append('  <!--')
    lines.append('       FLOATING BASE CONVENTION:')
    lines.append('       The root link "base_link" (CAD segment "trunk") has NO parent joint.')
    lines.append('       This is the standard floating-base URDF:')
    lines.append('         * PyBullet: p.loadURDF(..., useFixedBase=False) gives the 6-DOF')
    lines.append('           free base (3 pos + 3 rot) automatically.')
    lines.append('         * ROS: a world -> base_link floating (virtual 6-DOF) joint is')
    lines.append('           added by the loader; URDF itself has no world joint.')
    lines.append('  -->')
    lines.append('')

    # ---------------- links ----------------
    for lk in links_src:
        src = lk["name"]
        uname = urdf_name(src)
        d = iner_links[src]
        com = d["com_m"]
        mass_kg = d["mass_g"] / 1000.0
        M = d["inertia_kgm2"]  # 3x3 symmetric

        lines.append(f'  <link name="{uname}">')
        # visual (mesh already modelled in the link frame; identity origin)
        lines.append('    <visual>')
        lines.append('      <origin xyz="0 0 0" rpy="0 0 0"/>')
        lines.append('      <geometry>')
        lines.append(f'        <mesh filename="../meshes/visual/{src}.stl"/>')
        lines.append('      </geometry>')
        lines.append('    </visual>')
        # collision
        lines.append('    <collision>')
        lines.append('      <origin xyz="0 0 0" rpy="0 0 0"/>')
        lines.append('      <geometry>')
        lines.append(f'        <mesh filename="../meshes/collision/{src}_col.stl"/>')
        lines.append('      </geometry>')
        lines.append('    </collision>')
        # extra sole contact box for the feet (shin_L / shin_R)
        if src in ("shin_L", "shin_R"):
            lines.append('    <collision>')
            lines.append('      <origin xyz="0 0 -0.054" rpy="0 0 0"/>')
            lines.append('      <geometry>')
            lines.append('        <!-- 40x44x4 mm sole contact geom, flat on ground in zero pose -->')
            lines.append('        <box size="0.020 0.022 0.002"/>')
            lines.append('      </geometry>')
            lines.append('    </collision>')
        # inertial
        lines.append('    <inertial>')
        lines.append(f'      <origin xyz="{fmt(com[0])} {fmt(com[1])} {fmt(com[2])}" rpy="0 0 0"/>')
        lines.append(f'      <mass value="{fmt(mass_kg)}"/>')
        lines.append(
            '      <inertia '
            f'ixx="{fmt(M[0][0])}" ixy="{fmt(M[0][1])}" ixz="{fmt(M[0][2])}" '
            f'iyy="{fmt(M[1][1])}" iyz="{fmt(M[1][2])}" '
            f'izz="{fmt(M[2][2])}"/>'
        )
        lines.append('    </inertial>')
        lines.append('  </link>')
        lines.append('')

    # ---------------- joints ----------------
    for j in joints:
        src_parent = j["parent"]
        src_child = j["child"]
        # source joint origin == child frame global placement; URDF wants parent-relative
        global_child_mm = frame_origin_mm[src_child]
        global_parent_mm = frame_origin_mm[src_parent]
        rel_mm = [global_child_mm[i] - global_parent_mm[i] for i in range(3)]
        origin_m = [v / 1000.0 for v in rel_mm]
        axis = j["axis"]
        lo_rad = deg2rad(j["limit_deg"][0])
        hi_rad = deg2rad(j["limit_deg"][1])
        eff = j["effort_nm"]
        vel_rad_s = deg2rad(j["velocity_deg_s"])

        lines.append(f'  <joint name="{j["name"]}" type="{j["type"]}">')
        lines.append(f'    <parent link="{urdf_name(src_parent)}"/>')
        lines.append(f'    <child link="{urdf_name(src_child)}"/>')
        lines.append(
            f'    <origin xyz="{fmt(origin_m[0])} {fmt(origin_m[1])} {fmt(origin_m[2])}" rpy="0 0 0"/>'
        )
        lines.append(f'    <axis xyz="{axis[0]} {axis[1]} {axis[2]}"/>')
        lines.append(
            '    <limit '
            f'lower="{fmt(lo_rad)}" upper="{fmt(hi_rad)}" '
            f'effort="{fmt(eff)}" velocity="{fmt(vel_rad_s)}"/>'
        )
        lines.append('  </joint>')
        lines.append('')

    lines.append('</robot>')
    lines.append('')

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return OUT_PATH


if __name__ == "__main__":
    p = build()
    print("WROTE:", p)
